import '@/style/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-stone-200 font-mono'>
        {children}
      </body>
    </html>
  )
}
